/* Generated by configure: do not edit manually */
#pragma once

/* Choose the right endian header */
#if defined(HAVE_ENDIAN_H)
  #include <endian.h>
#elif defined(HAVE_MACHINE_ENDIAN_H)
  #include <machine/endian.h>
#elif defined(HAVE_SYS_ENDIAN_H)
  #include <sys/endian.h>
#endif

#if !HAVE_DECL_BE64TOH
/* https://gist.github.com/yinyin/2027912 */
  #ifdef __APPLE__
    #include <libkern/OSByteOrder.h>
    #define be64toh(x) OSSwapBigToHostInt64(x)
  #else
    #error be64toh not available
  #endif
#endif
