/* Generated by configure: do not edit manually */
#pragma once

/* Choose the right endian header */
#if defined(HAVE_ENDIAN_H)
  #include <endian.h>
#elif defined(HAVE_MACHINE_ENDIAN_H)
  #include <machine/endian.h>
#elif defined(HAVE_SYS_ENDIAN_H)
  #include <sys/endian.h>
#endif

/* TODO: Provide fallback if be64toh is unavailable */
#if !defined(HAVE_DECL_BE64TOH)
#error be64toh not available
#endif
